### ISSUE TITLE
Add support for redshift

### ISSUE THREAD

**Issue by dimberman** [astro-projects/astro#87] opened 2022-02-07 16:16 UTC
Acceptance criteria:
- All current functions work with Redshift

**Comment by tatiana** [comment] 2022-02-23 21:53
Suggestion from @ashb : https://github.com/apache/airflow/pull/19137

**Comment by tatiana** [comment] 2022-02-24 00:37
This ticket is a duplicate of #58  and #60

**Closed by tatiana** 2022-02-24 00:37 UTC
Labels: duplicate, priority/critical
