### ISSUE TITLE
Standardize Astro backend around SQLAlchemy

### ISSUE THREAD

**Issue by dimberman** [astro-projects/astro#35] opened 2022-01-19 05:27 UTC
In order to support a wide audience, we should add support for BigQuery and Redshift. To prepare for these integrations, we should change our backend to use SQLAlchemy, which has support for many databases.

This ticket will involve changing the existing integrations to use SQLAlchemy, it does not involve adding new integrations

**Comment by tatiana** [comment] 2022-01-26 23:53
@dimberman is this a duplicate of #36?

**Closed** 2022-02-21 12:12 UTC
Labels: duplicate
